### ISSUE TITLE
Unused imports in generated code

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2729]
The following dependencies in `temp/Cargo.toml` don't seem to be used in the generated code. Can we remove them or are they used in some situations?

```toml
geo = { version = "0.26.0" }
geo-types = { version = "0.7" }
chrono = { version = "0.4.38" }
num = { version = "0.4.1" }
```
