### ISSUE TITLE
Feldera GUI causes the following error "crypto.randomUUID is not a function"

### ISSUE THREAD

**Issue by ytooyama** [feldera/feldera#3113]
Thank you for always providing useful software.
I will report the issue because there was a problem while using it.

**Describe the bug**
Feldera GUI causes the following error "crypto.randomUUID is not a function"

**To Reproduce**
1. Set the allowed-origins

```
    ports:
      # If you change the host side of the port mapping here, don't forget to
      # also add a corresponding --allowed-origins argument to the pipeline
      # manager command below (e.g., --allowed-origins "http://localhost:xyz").
      # Otherwise, browsers will complain about CORS errors
      - "28080:8080"
      - "28081:8081"
    command:
      - --allowed-origins
      - "http://172.17.28.65:28080"
```

3. `docker compose up -d`
4. Create `demo` pipeline 
5. If you open the URL of the existing pipeline directly, you can display the GUI without any problems.

ex.
- http://172.17.28.65:28080/pipelines/demo/

6. On the other hand, when you try to access a pipeline or root directory that does not exist, the following error is displayed.

ex.
- http://172.17.28.65:28080/pipelines/
- http://172.17.28.65:28080/

7. See error
Uncaught TypeError: crypto.randomUUID is not a function

**Expected behavior**
The screen is displayed no matter which address you access.
<img width="1181" alt="s1" src="https://github.com/user-attachments/assets/1a98b2c6-151e-497a-81a9-be7d7457a763">

**Screenshots**
Error displayed: 
<img width="1545" alt="s0" src="https://github.com/user-attachments/assets/0e7b2a0d-5c42-4f87-a230-9a311458e05e">

**Context (please complete the following information):**
 - Feldera Version: 0.31.0
 - Environment: Docker
 - Browser: Firefox, Safari
 - Pipeline Configuration/SQL code: https://docs.feldera.com/tutorials/basics/part1

**Additional context**

**Comment by ytooyama** [comment]
I thought it was because of Adblock, so I disabled the extension and tried again, but the symptoms were the same.

**Comment by lalithsuresh** [comment]
@Karakatiza666 could you take a look?

**Comment by rodonile** [comment]
Same issue on my side, I'm running from source and checked on firefox and chrome.

**Comment by Karakatiza666** [comment]
@rodonile Does URL http://172.17.28.65:28080 cause the issue for you, too? (Without the trailing slash)

**Comment by rodonile** [comment]
Actually yes, just tried it now

**Comment by Karakatiza666** [comment]
The issue seems to be the same with this one:
https://github.com/cypress-io/cypress/issues/14600

I would advise changing the `network.proxy.allow_hijacking_localhost` setting in `about:config` menu in the browser, as per the tread I linked. In the meantime I am working to reproduce the issue and provide a more definitive answer.

**Comment by lalithsuresh** [comment]
@ytooyama @rodonile we issued a fix and it's been included in the 0.32.0 release. Let us know if the fix works for you, thanks!

**Comment by ytooyama** [comment]
It will also be reproduced in the new version.

```
% cat deploy/docker-compose.yml                    
name: feldera
services:
  pipeline-manager:
    tty: true
    image: ghcr.io/feldera/pipeline-manager:${FELDERA_VERSION:-0.31.2}
    ports:
      # If you change the host side of the port mapping here, don't forget to
      # also add a corresponding --allowed-origins argument to the pipeline
      # manager command below (e.g., --allowed-origins "http://localhost:xyz").
      # Otherwise, browsers will complain about CORS errors
      - "28080:8080"
      - "28081:8081"
    command:
      - --allowed-origins
      - "http://192.168.1.5:28080"

% docker compose -f deploy/docker-compose.yml up -d
```

Results:

<img width="1481" alt="shot3" src="https://github.com/user-attachments/assets/0f5bbf00-4e7b-43eb-b72f-387be6c8e0bc">
