### ISSUE TITLE
Debezium connector configuration dialog

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#813]
Implement a Debezium connector dialog to create or modify a new _input_ connector.

## Background

Debezium isn't truly a new connector type.  It is just a Kafka transport connector with all the same transport options we have for Kafka and a different set of supported formats (for now, just one). 

Here is an example yaml config generated for this connector (sorry that this is not JSON, this was easier for me to extract, but JSON is equivalent).

```yaml
    transport:
      name: kafka
      config:
        auto.offset.reset: earliest
        topics:
        - inventory.inventory.addresses
    format:
      name: json
      config:
        json_flavor: debezium_mysql
        update_format: debezium
```

The `transport` section is just a standard Kafka transport config.  The `format` section specifies the `json` format, with `update_format` set to "debezium" (our normal JSON format config dialog supports "raw" and "insert_delete" format) and the an additional `json_flavor` field that specifies the flavor of Debezium connector used (we only support MySQL now).

## Design

- [ ] Add a new `Debezium` input connector type to WebConsole. Since this is just a Kafka connector, the WebConsole must rely on the `update_format` field to distinguish it from normal Kafka connectors when listing connectors or when opening a connector edit dialog.
- [ ] The config dialog is based on the Kafka config dialog with the following changes:
   - "New Kafka Datasource" -> "New Debezium Datasource"
   - "Add a Kafka Input" -> "Add a Debezium input"
   - `METADATA` section: add a "Source Database" dropdown list.  The only option available now is MySQL.  This field determines the value of the `json_flavor` config field.
   - `Server` and `security tabs` - no modifications.
   - `Format` tab only has one config option: `Data format`, and the only supported data format is "JSON" (we will add "AVRO" in the future, so maybe we can show it as a disabled option).
