### ISSUE TITLE
Snowflake connector configuration dialog

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#859]
The design is very similar to what we did for Debezium, except that this is based on the output Kafka connector, not input.  

Example config this connector should produce:

```yaml
    stream: PREFERRED_VENDOR
    transport:
      name: kafka
      config:
        topic: snowflake.preferred_vendor
    format:
      name: json
      config:
        update_format: snowflake
    max_buffered_records: 1000000
```

The `transport` section is just a standard Kafka transport config.  The `format` section specifies the `json` format, with `update_format` set to "snowflake" (our normal JSON format config dialog does not allow choosing update format).

## Design

- [ ] Add a new `Kafka-Snowflake` output connector type to WebConsole. Since this is just a Kafka connector, the WebConsole must rely on the `update_format` field to distinguish it from normal Kafka connectors when listing connectors or when opening a connector edit dialog.
- [ ] The config dialog is based on the Kafka config dialog with the following changes:
   - "New Kafka Output" -> "New Kafka-Snowflake output"
   - "Add a Kafka output" -> "Output to a Snowflake table via a Kafka topic"
   - `Details`, `Server` and `security` tabs - no modifications.
   - `Format` tab only has one config option: `Data format`, and the only supported data format is "JSON" (we will add "AVRO" in the future, so maybe we can show it as a disabled option).
